version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/conf:/etc/letsencrypt:ro
            - ./certbot/www:/var/www/certbot:ro
        user: root
        #command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        depends_on:
            - socket-server
        networks:
            - app_network

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1d & wait $${!}; done;'"

    socket-server:
        build: .
        env_file:
            - .env.prod
        expose:
            - '3003'
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - app_network
        restart: unless-stopped

    redis:
        image: redis:alpine
        command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
        volumes:
            - redis_data:/data
        expose:
            - '6379'
        networks:
            - app_network
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    redis_data:

networks:
    app_network:
        driver: bridge
